### ISSUE TITLE
Default to master configuration unless specified in slave.

### ISSUE THREAD

**Issue by joshuapinter** [rocketjob/active_record_slave#13]
To keep things DRY, what do you think about defaulting to the master's database configuration unless specified in the slave configuration. For the example in your README:

```yml
production:
  database: production
  username: username
  password: password
  encoding: utf8
  adapter:  mysql
  host:     master1
  pool:     50
  slave:
    database: production
    username: username
    password: password
    encoding: utf8
    adapter:  mysql
    host:     slave1
    pool:     50
```

Typically with slave databases, most of the settings are actually the exact same as the master, except for host (usually). 

Wouldn't it be nice to write this instead: 

```yml
production:
  database: production
  username: username
  password: password
  encoding: utf8
  adapter:  mysql
  host:     master1
  pool:     50
  slave:
    host: slave1
```

And have the slave configuration just inherit from the master configuration?

Let me know what you think and I'll look at doing a PR.

Thanks!

### Environment

Provide at least:
* Ruby Version.
```bash
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
```

* Active Record Slave Version.
`1.4.0`

* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.).
Rails

* Full Stack Trace, if an exception is being raised.
```
Traceback (most recent call last):
  43: from bin/rails:4:in `<main>'
  42: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  41: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
  40: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
  39: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  38: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  37: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  36: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  35: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  34: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/commands.rb:17:in `<main>'
  33: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  32: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:67:in `console'
  31: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
  30: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
  29: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  28: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
  27: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
  26: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/skylight-core-3.1.2/lib/skylight/core/probes.rb:119:in `require'
  25: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  24: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  23: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  22: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  21: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  20: from /Users/me/Development/cntral/config/environment.rb:5:in `<main>'
  19: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `method_missing'
  18: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `public_send'
  17: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
  16: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
  15: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  14: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  13: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  12: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
  11: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
  10: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
   9: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
   8: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
   7: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
   6: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
   5: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
   4: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
   3: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/active_record_slave-1.4.0/lib/active_record_slave/railtie.rb:21:in `block in <class:Railtie>'
   2: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/active_record_slave-1.4.0/lib/active_record_slave/active_record_slave.rb:24:in `install!'
   1: from /Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:50:in `establish_connection'
/Users/me/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/connection_specification.rb:171:in `spec': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
```

**Comment by reidmorrison** [comment]
Yes, I considered it. Since the slave config would always inherit from the master config, it would remove the ability to have a slave be a completely different database, where the keys from the master would conflict.

To dry up the `database.yml` we use yaml aliases: https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)

**Comment by joshuapinter** [comment]
Excellent. Thanks for the response. 

We’ve used YAML aliases in the past for shared environment configs but the proposed change will be so much cleaner and clearer. 

I’ll see what I can do to carve out some time.

**Comment by joshuapinter** [comment]
Wait, I think I misunderstood your reply. Are you saying you are completely against it or are you saying that you would be interested in a PR for this functionality?

Thanks!

**Comment by joshuapinter** [comment]
See https://github.com/rocketjob/active_record_slave/pull/14 for a PR to do this. We tested this and are using it in our Rails 4.2 application (Ruby 2.5.3) and it works great.
